# Generated by Django 5.1.2 on 2024-10-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetotext', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocraws',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
